"""Type stubs for native OxyRoute Rust PyO3 extension module (_oxyroute)."""

from collections.abc import Coroutine
from typing import Any

class App:
    def __init__(self, include_openapi: bool = True) -> None: ...
    def add_route(
        self,
        method: str,
        path: str,
        handler: Any,
        require_jwt: bool = False,
        jwt_secret: str | None = None,
        algorithms: list[str] | None = None,
        read_json_body: bool = True,
        read_form_body: bool = False,
        dependencies: list[tuple[str, Any]] | None = None,
        jwt_issuer: str | None = None,
        jwt_audience: str | None = None,
        jwt_leeway: int | None = None,
        jwt_cookie: str | None = None,
        body_schema_json: str | None = None,
        body_model: Any | None = None,
        tags: list[str] | None = None,
        body_param_name: str | None = None,
    ) -> None: ...
    def add_websocket_route(self, path: str, handler: Any) -> None: ...
    def freeze(self) -> None: ...
    def set_openapi_served(self, enabled: bool) -> None: ...
    def set_openapi_title(self, title: str) -> None: ...
    def set_openapi_info(
        self,
        description: str | None = None,
        contact_json: str | None = None,
        servers_json: str | None = None,
    ) -> None: ...
    def add_exception_handler(self, exc_type: type[BaseException], handler: Any) -> None: ...
    def setup_database(
        self,
        url: str,
        min_connections: int = 1,
        max_connections: int = 10,
        acquire_timeout_secs: float = 30.0,
        idle_timeout_secs: float = 600.0,
        max_lifetime_secs: float = 1800.0,
    ) -> Coroutine[Any, Any, None]: ...
    def close_database(self) -> Coroutine[Any, Any, None]: ...
    def handle_rsgi(self, scope: Any, protocol: Any) -> Any: ...
    def openapi_json(self) -> str: ...

class PyDepends:
    def __init__(self, call: Any) -> None: ...
    def dependency(self) -> Any: ...

class WebSocket:
    @property
    def scope(self) -> dict[str, Any]: ...
    @property
    def path_params(self) -> dict[str, str]: ...
    @property
    def is_closed(self) -> bool: ...
    async def accept(self) -> None: ...
    async def receive(self) -> str | bytes: ...
    async def receive_text(self) -> str: ...
    async def receive_bytes(self) -> bytes: ...
    async def send_text(self, data: str) -> None: ...
    async def send_bytes(self, data: bytes) -> None: ...
    async def send_json(self, data: Any) -> None: ...
    async def close(self, code: int | None = None) -> None: ...

class DBQuery:
    query: str
    args: tuple[Any, ...]
    def __init__(self, query: str, args: tuple[Any, ...] | list[Any] | None = None) -> None: ...

def decode_jwt_hs(
    token: str,
    key: str,
    algorithm_list: list[str],
) -> dict[str, Any]: ...
